In [1]:
import os
import psycopg
import pandas as pd
import mlflow
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder, 
    SplineTransformer, 
    QuantileTransformer, 
    RobustScaler,
    PolynomialFeatures,
    KBinsDiscretizer,
)

In [2]:
TABLE_NAME = "clean_users_churn"

In [3]:
TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

In [4]:
EXPERIMENT_NAME = "WORK_WITH_FEATURES"
RUN_NAME = "preprocessing"
REGISTRY_MODEL_NAME = "PREPROCESSED_MODEL"

In [5]:
connection = {"sslmode": "require", "target_session_attrs": "read-write"}
postgres_credits = {
    "host": os.getenv("DB_DESTINATION_HOST"),
    "port": os.getenv("DB_DESTINATION_PORT"),
    "dbname": os.getenv("DB_DESTINATION_NAME"),
    "user": os.getenv("DB_DESTINATION_USER"),
    "password": os.getenv("DB_DESTINATION_PASSWORD")
}

connection.update(postgres_credits)

In [6]:
with psycopg.connect(**connection) as conn:
    with conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {TABLE_NAME}")

        data = cur.fetchall()

        columns = [column[0] for column in cur.description]

df = pd.DataFrame(data=data, columns=columns)

In [7]:
df

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,device_protection,tech_support,streaming_tv,streaming_movies,gender,senior_citizen,partner,dependents,multiple_lines,target
0,28,1680-VDCWW,2019-02-01,NaT,One year,No,Bank transfer (automatic),19.80,202.25,Fiber optic,...,No,No,No,No,Male,0,Yes,No,No,0
1,29,1066-JKSGK,2019-11-01,2019-12-01,Month-to-month,No,Mailed check,20.15,20.15,Fiber optic,...,No,No,No,No,Male,0,No,No,No,1
2,30,3638-WEABW,2015-04-01,NaT,Two year,Yes,Credit card (automatic),59.90,3505.10,DSL,...,No,Yes,No,No,Female,0,Yes,No,Yes,0
3,31,6322-HRPFA,2016-01-01,NaT,Month-to-month,No,Credit card (automatic),59.60,2970.30,DSL,...,No,Yes,No,No,Male,0,Yes,Yes,No,0
4,32,6865-JZNKO,2017-08-01,NaT,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.60,DSL,...,No,No,No,No,Female,0,No,No,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7019,6989,1264-FUHCX,2018-03-01,NaT,Month-to-month,Yes,Credit card (automatic),69.50,1652.10,DSL,...,No,Yes,Yes,No,Female,0,Yes,Yes,Yes,0
7020,6990,7789-CRUVC,2018-06-01,NaT,One year,No,Bank transfer (automatic),76.00,1588.75,DSL,...,No,No,Yes,Yes,Female,0,Yes,Yes,Yes,0
7021,6991,6598-KELSS,2017-02-01,NaT,Month-to-month,Yes,Electronic check,93.60,3366.05,Fiber optic,...,No,No,Yes,Yes,Male,0,Yes,No,No,0
7022,6992,8739-WWKDU,2019-03-01,2019-11-01,Month-to-month,No,Bank transfer (automatic),95.65,778.10,Fiber optic,...,No,No,Yes,Yes,Female,0,No,No,Yes,1
7023,6993,8685-WHQPW,2014-03-01,NaT,One year,No,Bank transfer (automatic),100.55,7113.75,Fiber optic,...,No,No,Yes,Yes,Male,0,Yes,Yes,Yes,0

In [8]:
obj_df = df.select_dtypes(include=["object"])

In [7]:
cat_columns = ["type", "payment_method", "internet_service", "gender"]

In [ ]:
encoder_oh = OneHotEncoder(categories="auto", handle_unknown="error", max_categories=15, drop="first", sparse_output=False)

In [9]:
num_columns = ["monthly_charges", "total_charges"]
n_knots = 3
degree_spline = 4
n_quantiles=100
degree = 3
n_bins = 5
encode = 'ordinal'
strategy = 'uniform'
subsample = None

In [10]:
# SplineTransformer
encoder_spl = SplineTransformer(n_knots=n_knots, degree=degree_spline)

# QuantileTransformer
encoder_q = QuantileTransformer(n_quantiles=n_quantiles)

# RobustScaler
encoder_rb = RobustScaler()

# PolynomialFeatures
encoder_pol = PolynomialFeatures(degree=degree)

# KBinsDiscretizer
encoder_kbd = KBinsDiscretizer(n_bins=n_bins, encode=encode, strategy=strategy, subsample=subsample)

In [11]:
numeric_transformer = ColumnTransformer(
    transformers=[
        ("spl", encoder_spl, num_columns),
        ("q", encoder_q, num_columns),
        ("rb", encoder_rb, num_columns),
        ("pol", encoder_pol, num_columns),
        ("kbd", encoder_kbd, num_columns),
]
)

categorical_transformer = Pipeline(steps=[('encoder', encoder_oh)])

preprocessor = ColumnTransformer(
	    transformers=[
            ("num", numeric_transformer, num_columns),
            ("cat", categorical_transformer, cat_columns)
        ],
    n_jobs=-1
)

encoded_features = preprocessor.fit_transform(df)

transformed_df = pd.DataFrame(encoded_features, columns=preprocessor.get_feature_names_out())

df = pd.concat([df, transformed_df], axis=1)

In [1]:
df

NameError: name 'df' is not defined

In [23]:
preprocessor

ColumnTransformer(n_jobs=-1,
                  transformers=[('num',
                                 ColumnTransformer(transformers=[('spl',
                                                                  SplineTransformer(degree=4,
                                                                                    n_knots=3),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('q',
                                                                  QuantileTransformer(n_quantiles=100),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('rb',
                                                                  RobustScaler(),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('pol',
                                                                  PolynomialFeatures(degree=3),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('kbd',
                                                                  KBinsDiscretizer(encode='ordinal',
                                                                                   strategy='uniform',
                                                                                   subsample=None),
                                                                  ['monthly_charges',
                                                                   'total_charges'])]),
                                 ['monthly_charges', 'total_charges']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(drop='first',
                                                                max_categories=15,
                                                                sparse_output=False))]),
                                 ['type', 'payment_method', 'internet_service',
                                  'gender'])])

In [ ]:
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "https://storage.yandexcloud.net"

In [13]:
mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

In [18]:
experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

In [17]:
if not experiment_id:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

In [19]:
with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    mlflow.sklearn.log_model(preprocessor, "column_transformer")

2026/01/14 07:18:07 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!

In [21]:
df

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,num__pol__total_charges^3,num__kbd__monthly_charges,num__kbd__total_charges,cat__type_One year,cat__type_Two year,cat__payment_method_Credit card (automatic),cat__payment_method_Electronic check,cat__payment_method_Mailed check,cat__internet_service_Fiber optic,cat__gender_Male
0,28,1680-VDCWW,2019-02-01,NaT,One year,No,Bank transfer (automatic),19.80,202.25,Fiber optic,...,8.273049e+06,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
1,29,1066-JKSGK,2019-11-01,2019-12-01,Month-to-month,No,Mailed check,20.15,20.15,Fiber optic,...,8.181353e+03,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,30,3638-WEABW,2015-04-01,NaT,Two year,Yes,Credit card (automatic),59.90,3505.10,DSL,...,4.306270e+10,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
3,31,6322-HRPFA,2016-01-01,NaT,Month-to-month,No,Credit card (automatic),59.60,2970.30,DSL,...,2.620601e+10,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,32,6865-JZNKO,2017-08-01,NaT,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.60,DSL,...,3.585792e+09,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7019,6989,1264-FUHCX,2018-03-01,NaT,Month-to-month,Yes,Credit card (automatic),69.50,1652.10,DSL,...,4.509299e+09,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7020,6990,7789-CRUVC,2018-06-01,NaT,One year,No,Bank transfer (automatic),76.00,1588.75,DSL,...,4.010206e+09,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7021,6991,6598-KELSS,2017-02-01,NaT,Month-to-month,Yes,Electronic check,93.60,3366.05,Fiber optic,...,3.813833e+10,3.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
7022,6992,8739-WWKDU,2019-03-01,2019-11-01,Month-to-month,No,Bank transfer (automatic),95.65,778.10,Fiber optic,...,4.710926e+08,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7023,6993,8685-WHQPW,2014-03-01,NaT,One year,No,Bank transfer (automatic),100.55,7113.75,Fiber optic,...,3.599944e+11,4.0,4.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0

In [27]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(df, df["target"])

In [30]:
y_train

5404    0
6954    1
2510    0
6618    0
5841    0
       ..
5050    0
2241    0
5458    0
4659    0
2915    1
Name: target, Length: 5268, dtype: int64

In [29]:
X_train

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,num__pol__total_charges^3,num__kbd__monthly_charges,num__kbd__total_charges,cat__type_One year,cat__type_Two year,cat__payment_method_Credit card (automatic),cat__payment_method_Electronic check,cat__payment_method_Mailed check,cat__internet_service_Fiber optic,cat__gender_Male
5404,5599,5546-BYZSM,2017-07-01,NaT,One year,Yes,Credit card (automatic),75.50,2424.45,DSL,...,1.425081e+10,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
6954,4991,4482-FTFFX,2016-12-01,2019-12-01,Month-to-month,Yes,Bank transfer (automatic),97.35,3457.90,Fiber optic,...,4.134636e+10,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2510,2614,1265-BCFEO,2014-02-01,NaT,Two year,Yes,Electronic check,114.90,8496.70,Fiber optic,...,6.134100e+11,4.0,4.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
6618,6853,1036-GUDCL,2014-08-01,NaT,Two year,No,Bank transfer (automatic),65.70,4378.90,DSL,...,8.396438e+10,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5841,6089,3055-OYMSE,2020-01-01,NaT,Month-to-month,Yes,Credit card (automatic),49.80,49.80,DSL,...,1.235060e+05,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5050,5246,2282-YGNOR,2017-12-01,NaT,Month-to-month,Yes,Credit card (automatic),54.75,1406.90,DSL,...,2.784772e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2241,2342,2774-LVQUS,2018-01-01,NaT,One year,Yes,Mailed check,26.80,733.55,Fiber optic,...,3.947200e+08,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
5458,5654,9801-GDWGV,2017-10-01,NaT,One year,Yes,Electronic check,39.10,1096.60,DSL,...,1.318696e+09,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4659,4810,0366-NQSHS,2015-08-01,NaT,Two year,No,Electronic check,80.60,4299.95,DSL,...,7.950423e+10,3.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2915,3036,5795-KTGUD,2019-11-01,2020-01-01,Month-to-month,Yes,Electronic check,30.40,78.65,DSL,...,4.865149e+05,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [24]:
model = CatBoostClassifier(iterations=1000,
                           learning_rate=0.01,
                           )

In [25]:
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", model)
])

In [31]:
pipeline.fit(X_train, y_train)

0:	learn: 0.6862796	total: 60.4ms	remaining: 1m
1:	learn: 0.6797384	total: 67.4ms	remaining: 33.6s
2:	learn: 0.6730482	total: 74.4ms	remaining: 24.7s
3:	learn: 0.6668782	total: 81.3ms	remaining: 20.2s
4:	learn: 0.6608446	total: 88.2ms	remaining: 17.5s
5:	learn: 0.6555562	total: 95.8ms	remaining: 15.9s
6:	learn: 0.6508641	total: 103ms	remaining: 14.5s
7:	learn: 0.6449942	total: 109ms	remaining: 13.5s
8:	learn: 0.6395732	total: 116ms	remaining: 12.8s
9:	learn: 0.6342160	total: 123ms	remaining: 12.1s
10:	learn: 0.6290411	total: 130ms	remaining: 11.7s
11:	learn: 0.6240464	total: 137ms	remaining: 11.2s
12:	learn: 0.6196379	total: 143ms	remaining: 10.9s
13:	learn: 0.6156811	total: 149ms	remaining: 10.5s
14:	learn: 0.6117194	total: 156ms	remaining: 10.2s
15:	learn: 0.6071651	total: 162ms	remaining: 9.99s
16:	learn: 0.6026404	total: 169ms	remaining: 9.78s
17:	learn: 0.5977879	total: 178ms	remaining: 9.7s
18:	learn: 0.5931686	total: 184ms	remaining: 9.5s
19:	learn: 0.5897005	total: 190ms	remaining: 9.33s
20:	learn: 0.5862136	total: 197ms	remaining: 9.18s
21:	learn: 0.5823705	total: 203ms	remaining: 9.03s
22:	learn: 0.5784461	total: 209ms	remaining: 8.9s
23:	learn: 0.5745615	total: 216ms	remaining: 8.79s
24:	learn: 0.5705164	total: 223ms	remaining: 8.68s
25:	learn: 0.5664272	total: 228ms	remaining: 8.56s
26:	learn: 0.5634388	total: 234ms	remaining: 8.44s
27:	learn: 0.5602383	total: 241ms	remaining: 8.35s
28:	learn: 0.5567622	total: 247ms	remaining: 8.27s
29:	learn: 0.5542459	total: 253ms	remaining: 8.19s
30:	learn: 0.5517415	total: 261ms	remaining: 8.15s
31:	learn: 0.5486852	total: 267ms	remaining: 8.07s
32:	learn: 0.5455180	total: 274ms	remaining: 8.02s
33:	learn: 0.5425781	total: 280ms	remaining: 7.96s
34:	learn: 0.5402008	total: 286ms	remaining: 7.9s
35:	learn: 0.5373326	total: 293ms	remaining: 7.84s
36:	learn: 0.5350994	total: 299ms	remaining: 7.79s
37:	learn: 0.5322143	total: 306ms	remaining: 7.74s
38:	learn: 0.5294294	total: 312ms	remaining: 7.69s
39:	learn: 0.5271165	total: 319ms	remaining: 7.65s
40:	learn: 0.5251423	total: 325ms	remaining: 7.61s
41:	learn: 0.5224874	total: 334ms	remaining: 7.61s
42:	learn: 0.5206818	total: 340ms	remaining: 7.58s
43:	learn: 0.5183878	total: 347ms	remaining: 7.54s
44:	learn: 0.5166482	total: 354ms	remaining: 7.5s
45:	learn: 0.5146821	total: 360ms	remaining: 7.47s
46:	learn: 0.5124375	total: 367ms	remaining: 7.45s
47:	learn: 0.5105800	total: 374ms	remaining: 7.42s
48:	learn: 0.5092729	total: 381ms	remaining: 7.4s
49:	learn: 0.5075985	total: 388ms	remaining: 7.38s
50:	learn: 0.5058574	total: 396ms	remaining: 7.37s
51:	learn: 0.5043809	total: 405ms	remaining: 7.38s
52:	learn: 0.5025051	total: 412ms	remaining: 7.36s
53:	learn: 0.5011479	total: 418ms	remaining: 7.32s
54:	learn: 0.4996455	total: 427ms	remaining: 7.33s
55:	learn: 0.4981275	total: 435ms	remaining: 7.33s
56:	learn: 0.4968778	total: 441ms	remaining: 7.3s
57:	learn: 0.4951545	total: 448ms	remaining: 7.27s
58:	learn: 0.4937582	total: 454ms	remaining: 7.24s
59:	learn: 0.4921076	total: 462ms	remaining: 7.24s
60:	learn: 0.4907505	total: 469ms	remaining: 7.22s
61:	learn: 0.4898984	total: 472ms	remaining: 7.14s
62:	learn: 0.4880294	total: 478ms	remaining: 7.11s
63:	learn: 0.4861301	total: 484ms	remaining: 7.08s
64:	learn: 0.4849695	total: 490ms	remaining: 7.05s
65:	learn: 0.4834772	total: 497ms	remaining: 7.03s
66:	learn: 0.4824107	total: 503ms	remaining: 7s
67:	learn: 0.4813358	total: 509ms	remaining: 6.98s
68:	learn: 0.4799171	total: 516ms	remaining: 6.96s
69:	learn: 0.4787777	total: 522ms	remaining: 6.94s
70:	learn: 0.4776349	total: 529ms	remaining: 6.92s
71:	learn: 0.4765578	total: 535ms	remaining: 6.89s
72:	learn: 0.4752549	total: 541ms	remaining: 6.87s
73:	learn: 0.4738396	total: 548ms	remaining: 6.85s
74:	learn: 0.4725679	total: 554ms	remaining: 6.83s
75:	learn: 0.4712410	total: 561ms	remaining: 6.82s
76:	learn: 0.4704476	total: 568ms	remaining: 6.81s
77:	learn: 0.4693621	total: 575ms	remaining: 6.8s
78:	learn: 0.4681950	total: 583ms	remaining: 6.8s
79:	learn: 0.4674391	total: 590ms	remaining: 6.78s
80:	learn: 0.4661894	total: 597ms	remaining: 6.77s
81:	learn: 0.4652391	total: 603ms	remaining: 6.75s
82:	learn: 0.4643671	total: 609ms	remaining: 6.73s
83:	learn: 0.4635827	total: 616ms	remaining: 6.71s
84:	learn: 0.4627338	total: 623ms	remaining: 6.7s
85:	learn: 0.4619650	total: 631ms	remaining: 6.7s
86:	learn: 0.4611989	total: 638ms	remaining: 6.69s
87:	learn: 0.4600925	total: 645ms	remaining: 6.68s
88:	learn: 0.4595119	total: 652ms	remaining: 6.67s
89:	learn: 0.4588112	total: 659ms	remaining: 6.66s
90:	learn: 0.4579742	total: 667ms	remaining: 6.66s
91:	learn: 0.4570662	total: 676ms	remaining: 6.67s
92:	learn: 0.4560079	total: 684ms	remaining: 6.67s
93:	learn: 0.4554787	total: 691ms	remaining: 6.66s
94:	learn: 0.4548694	total: 697ms	remaining: 6.64s
95:	learn: 0.4540546	total: 704ms	remaining: 6.63s
96:	learn: 0.4535138	total: 711ms	remaining: 6.62s
97:	learn: 0.4529235	total: 718ms	remaining: 6.61s
98:	learn: 0.4524624	total: 726ms	remaining: 6.61s
99:	learn: 0.4518239	total: 733ms	remaining: 6.6s
100:	learn: 0.4512603	total: 740ms	remaining: 6.58s
101:	learn: 0.4507113	total: 746ms	remaining: 6.57s
102:	learn: 0.4501659	total: 753ms	remaining: 6.55s
103:	learn: 0.4493114	total: 759ms	remaining: 6.54s
104:	learn: 0.4488283	total: 765ms	remaining: 6.52s
105:	learn: 0.4483188	total: 772ms	remaining: 6.51s
106:	learn: 0.4478552	total: 778ms	remaining: 6.49s
107:	learn: 0.4472863	total: 784ms	remaining: 6.48s
108:	learn: 0.4463814	total: 790ms	remaining: 6.46s
109:	learn: 0.4455550	total: 797ms	remaining: 6.45s
110:	learn: 0.4447423	total: 803ms	remaining: 6.43s
111:	learn: 0.4442867	total: 810ms	remaining: 6.42s
112:	learn: 0.4437611	total: 817ms	remaining: 6.41s
113:	learn: 0.4431118	total: 823ms	remaining: 6.4s
114:	learn: 0.4426905	total: 832ms	remaining: 6.4s
115:	learn: 0.4422675	total: 839ms	remaining: 6.39s
116:	learn: 0.4417457	total: 846ms	remaining: 6.38s
117:	learn: 0.4413185	total: 852ms	remaining: 6.37s
118:	learn: 0.4406065	total: 859ms	remaining: 6.36s
119:	learn: 0.4402818	total: 868ms	remaining: 6.36s
120:	learn: 0.4396611	total: 875ms	remaining: 6.36s
121:	learn: 0.4392589	total: 883ms	remaining: 6.35s
122:	learn: 0.4386462	total: 890ms	remaining: 6.34s
123:	learn: 0.4383139	total: 896ms	remaining: 6.33s
124:	learn: 0.4376034	total: 903ms	remaining: 6.32s
125:	learn: 0.4369737	total: 910ms	remaining: 6.31s
126:	learn: 0.4366133	total: 917ms	remaining: 6.3s
127:	learn: 0.4361106	total: 926ms	remaining: 6.31s
128:	learn: 0.4357419	total: 933ms	remaining: 6.3s
129:	learn: 0.4355011	total: 940ms	remaining: 6.29s
130:	learn: 0.4350108	total: 947ms	remaining: 6.28s
131:	learn: 0.4347017	total: 954ms	remaining: 6.27s
132:	learn: 0.4342974	total: 960ms	remaining: 6.26s
133:	learn: 0.4339081	total: 967ms	remaining: 6.25s
134:	learn: 0.4334598	total: 974ms	remaining: 6.24s
135:	learn: 0.4329108	total: 981ms	remaining: 6.23s
136:	learn: 0.4325883	total: 987ms	remaining: 6.22s
137:	learn: 0.4322494	total: 994ms	remaining: 6.21s
138:	learn: 0.4317572	total: 1s	remaining: 6.2s
139:	learn: 0.4314545	total: 1.01s	remaining: 6.19s
140:	learn: 0.4311709	total: 1.01s	remaining: 6.17s
141:	learn: 0.4309383	total: 1.02s	remaining: 6.16s
142:	learn: 0.4306592	total: 1.03s	remaining: 6.15s
143:	learn: 0.4302373	total: 1.03s	remaining: 6.14s
144:	learn: 0.4300386	total: 1.04s	remaining: 6.13s
145:	learn: 0.4297325	total: 1.05s	remaining: 6.12s
146:	learn: 0.4295166	total: 1.05s	remaining: 6.11s
147:	learn: 0.4291877	total: 1.06s	remaining: 6.11s
148:	learn: 0.4288073	total: 1.07s	remaining: 6.1s
149:	learn: 0.4285906	total: 1.07s	remaining: 6.09s
150:	learn: 0.4282519	total: 1.08s	remaining: 6.08s
151:	learn: 0.4280023	total: 1.09s	remaining: 6.07s
152:	learn: 0.4278066	total: 1.09s	remaining: 6.06s
153:	learn: 0.4276567	total: 1.1s	remaining: 6.05s
154:	learn: 0.4273962	total: 1.11s	remaining: 6.04s
155:	learn: 0.4270739	total: 1.11s	remaining: 6.03s
156:	learn: 0.4268603	total: 1.12s	remaining: 6.02s
157:	learn: 0.4265478	total: 1.13s	remaining: 6.02s
158:	learn: 0.4262395	total: 1.14s	remaining: 6.01s
159:	learn: 0.4260412	total: 1.14s	remaining: 6s
160:	learn: 0.4258307	total: 1.15s	remaining: 5.99s
161:	learn: 0.4255817	total: 1.16s	remaining: 5.99s
162:	learn: 0.4253729	total: 1.16s	remaining: 5.97s
163:	learn: 0.4251901	total: 1.17s	remaining: 5.97s
164:	learn: 0.4248098	total: 1.18s	remaining: 5.96s
165:	learn: 0.4246277	total: 1.18s	remaining: 5.95s
166:	learn: 0.4244067	total: 1.19s	remaining: 5.94s
167:	learn: 0.4242613	total: 1.2s	remaining: 5.93s
168:	learn: 0.4240762	total: 1.2s	remaining: 5.92s
169:	learn: 0.4238143	total: 1.21s	remaining: 5.91s
170:	learn: 0.4235373	total: 1.22s	remaining: 5.9s
171:	learn: 0.4231848	total: 1.22s	remaining: 5.89s
172:	learn: 0.4230116	total: 1.23s	remaining: 5.9s
173:	learn: 0.4228832	total: 1.24s	remaining: 5.89s
174:	learn: 0.4225990	total: 1.25s	remaining: 5.89s
175:	learn: 0.4224166	total: 1.25s	remaining: 5.88s
176:	learn: 0.4220968	total: 1.26s	remaining: 5.87s
177:	learn: 0.4219098	total: 1.27s	remaining: 5.87s
178:	learn: 0.4217870	total: 1.28s	remaining: 5.86s
179:	learn: 0.4215727	total: 1.28s	remaining: 5.85s
180:	learn: 0.4213647	total: 1.29s	remaining: 5.84s
181:	learn: 0.4212658	total: 1.3s	remaining: 5.84s
182:	learn: 0.4211411	total: 1.3s	remaining: 5.83s
183:	learn: 0.4210160	total: 1.31s	remaining: 5.82s
184:	learn: 0.4208989	total: 1.32s	remaining: 5.81s
185:	learn: 0.4207980	total: 1.33s	remaining: 5.81s
186:	learn: 0.4206640	total: 1.33s	remaining: 5.8s
187:	learn: 0.4205344	total: 1.34s	remaining: 5.79s
188:	learn: 0.4202593	total: 1.35s	remaining: 5.78s
189:	learn: 0.4201665	total: 1.35s	remaining: 5.77s
190:	learn: 0.4200232	total: 1.36s	remaining: 5.76s
191:	learn: 0.4198978	total: 1.37s	remaining: 5.75s
192:	learn: 0.4197654	total: 1.37s	remaining: 5.75s
193:	learn: 0.4195689	total: 1.38s	remaining: 5.74s
194:	learn: 0.4192408	total: 1.39s	remaining: 5.73s
195:	learn: 0.4190478	total: 1.39s	remaining: 5.72s
196:	learn: 0.4188208	total: 1.4s	remaining: 5.71s
197:	learn: 0.4186887	total: 1.41s	remaining: 5.7s
198:	learn: 0.4185571	total: 1.41s	remaining: 5.7s
199:	learn: 0.4184347	total: 1.42s	remaining: 5.69s
200:	learn: 0.4182721	total: 1.43s	remaining: 5.68s
201:	learn: 0.4180255	total: 1.44s	remaining: 5.67s
202:	learn: 0.4179593	total: 1.44s	remaining: 5.66s
203:	learn: 0.4178444	total: 1.45s	remaining: 5.65s
204:	learn: 0.4175935	total: 1.46s	remaining: 5.64s
205:	learn: 0.4175029	total: 1.46s	remaining: 5.64s
206:	learn: 0.4174036	total: 1.47s	remaining: 5.63s
207:	learn: 0.4172920	total: 1.48s	remaining: 5.62s
208:	learn: 0.4171080	total: 1.48s	remaining: 5.62s
209:	learn: 0.4169839	total: 1.49s	remaining: 5.61s
210:	learn: 0.4168992	total: 1.5s	remaining: 5.6s
211:	learn: 0.4167233	total: 1.5s	remaining: 5.59s
212:	learn: 0.4166138	total: 1.51s	remaining: 5.58s
213:	learn: 0.4163660	total: 1.52s	remaining: 5.57s
214:	learn: 0.4162353	total: 1.52s	remaining: 5.56s
215:	learn: 0.4161461	total: 1.53s	remaining: 5.56s
216:	learn: 0.4159517	total: 1.54s	remaining: 5.55s
217:	learn: 0.4158005	total: 1.54s	remaining: 5.54s
218:	learn: 0.4156305	total: 1.55s	remaining: 5.54s
219:	learn: 0.4155184	total: 1.56s	remaining: 5.53s
220:	learn: 0.4153955	total: 1.56s	remaining: 5.52s
221:	learn: 0.4152606	total: 1.57s	remaining: 5.51s
222:	learn: 0.4151820	total: 1.58s	remaining: 5.5s
223:	learn: 0.4150650	total: 1.59s	remaining: 5.5s
224:	learn: 0.4149550	total: 1.59s	remaining: 5.49s
225:	learn: 0.4148766	total: 1.6s	remaining: 5.48s
226:	learn: 0.4147290	total: 1.61s	remaining: 5.47s
227:	learn: 0.4146564	total: 1.61s	remaining: 5.46s
228:	learn: 0.4145823	total: 1.62s	remaining: 5.46s
229:	learn: 0.4144834	total: 1.63s	remaining: 5.45s
230:	learn: 0.4143899	total: 1.63s	remaining: 5.44s
231:	learn: 0.4142663	total: 1.64s	remaining: 5.43s
232:	learn: 0.4141086	total: 1.65s	remaining: 5.43s
233:	learn: 0.4140371	total: 1.66s	remaining: 5.42s
234:	learn: 0.4139122	total: 1.66s	remaining: 5.41s
235:	learn: 0.4138327	total: 1.67s	remaining: 5.41s
236:	learn: 0.4137382	total: 1.68s	remaining: 5.4s
237:	learn: 0.4136513	total: 1.69s	remaining: 5.4s
238:	learn: 0.4135550	total: 1.69s	remaining: 5.39s
239:	learn: 0.4134665	total: 1.7s	remaining: 5.38s
240:	learn: 0.4133588	total: 1.71s	remaining: 5.38s
241:	learn: 0.4132208	total: 1.71s	remaining: 5.37s
242:	learn: 0.4130205	total: 1.72s	remaining: 5.36s
243:	learn: 0.4129376	total: 1.73s	remaining: 5.35s
244:	learn: 0.4128066	total: 1.73s	remaining: 5.34s
245:	learn: 0.4126921	total: 1.74s	remaining: 5.34s
246:	learn: 0.4125295	total: 1.75s	remaining: 5.33s
247:	learn: 0.4124279	total: 1.75s	remaining: 5.32s
248:	learn: 0.4122549	total: 1.76s	remaining: 5.31s
249:	learn: 0.4121872	total: 1.77s	remaining: 5.3s
250:	learn: 0.4121222	total: 1.77s	remaining: 5.29s
251:	learn: 0.4119523	total: 1.78s	remaining: 5.28s
252:	learn: 0.4118454	total: 1.79s	remaining: 5.27s
253:	learn: 0.4117802	total: 1.79s	remaining: 5.26s
254:	learn: 0.4116164	total: 1.8s	remaining: 5.26s
255:	learn: 0.4115392	total: 1.8s	remaining: 5.25s
256:	learn: 0.4114297	total: 1.81s	remaining: 5.24s
257:	learn: 0.4113358	total: 1.82s	remaining: 5.24s
258:	learn: 0.4112438	total: 1.83s	remaining: 5.23s
259:	learn: 0.4111055	total: 1.83s	remaining: 5.22s
260:	learn: 0.4110247	total: 1.84s	remaining: 5.21s
261:	learn: 0.4109369	total: 1.85s	remaining: 5.2s
262:	learn: 0.4108578	total: 1.85s	remaining: 5.19s
263:	learn: 0.4107546	total: 1.86s	remaining: 5.18s
264:	learn: 0.4106997	total: 1.87s	remaining: 5.18s
265:	learn: 0.4106443	total: 1.88s	remaining: 5.17s
266:	learn: 0.4104787	total: 1.88s	remaining: 5.17s
267:	learn: 0.4103971	total: 1.89s	remaining: 5.16s
268:	learn: 0.4103080	total: 1.9s	remaining: 5.15s
269:	learn: 0.4102396	total: 1.9s	remaining: 5.14s
270:	learn: 0.4101528	total: 1.91s	remaining: 5.13s
271:	learn: 0.4100757	total: 1.92s	remaining: 5.13s
272:	learn: 0.4099036	total: 1.92s	remaining: 5.12s
273:	learn: 0.4098085	total: 1.93s	remaining: 5.11s
274:	learn: 0.4097430	total: 1.94s	remaining: 5.11s
275:	learn: 0.4096428	total: 1.94s	remaining: 5.1s
276:	learn: 0.4095496	total: 1.95s	remaining: 5.09s
277:	learn: 0.4095104	total: 1.96s	remaining: 5.08s
278:	learn: 0.4094424	total: 1.96s	remaining: 5.07s
279:	learn: 0.4093635	total: 1.97s	remaining: 5.07s
280:	learn: 0.4092476	total: 1.98s	remaining: 5.07s
281:	learn: 0.4091716	total: 1.99s	remaining: 5.06s
282:	learn: 0.4090670	total: 1.99s	remaining: 5.05s
283:	learn: 0.4089662	total: 2s	remaining: 5.05s
284:	learn: 0.4089125	total: 2.01s	remaining: 5.04s
285:	learn: 0.4087777	total: 2.01s	remaining: 5.03s
286:	learn: 0.4087099	total: 2.02s	remaining: 5.02s
287:	learn: 0.4086343	total: 2.03s	remaining: 5.01s
288:	learn: 0.4085806	total: 2.03s	remaining: 5s
289:	learn: 0.4084904	total: 2.04s	remaining: 5s
290:	learn: 0.4084515	total: 2.05s	remaining: 4.99s
291:	learn: 0.4083526	total: 2.05s	remaining: 4.98s
292:	learn: 0.4082050	total: 2.06s	remaining: 4.97s
293:	learn: 0.4081268	total: 2.07s	remaining: 4.96s
294:	learn: 0.4080828	total: 2.08s	remaining: 4.96s
295:	learn: 0.4079959	total: 2.08s	remaining: 4.95s
296:	learn: 0.4079495	total: 2.09s	remaining: 4.94s
297:	learn: 0.4078529	total: 2.09s	remaining: 4.93s
298:	learn: 0.4077933	total: 2.1s	remaining: 4.93s
299:	learn: 0.4077239	total: 2.11s	remaining: 4.92s
300:	learn: 0.4076799	total: 2.11s	remaining: 4.91s
301:	learn: 0.4076137	total: 2.12s	remaining: 4.91s
302:	learn: 0.4075805	total: 2.13s	remaining: 4.9s
303:	learn: 0.4075126	total: 2.13s	remaining: 4.89s
304:	learn: 0.4074235	total: 2.14s	remaining: 4.88s
305:	learn: 0.4073614	total: 2.15s	remaining: 4.87s
306:	learn: 0.4072714	total: 2.15s	remaining: 4.86s
307:	learn: 0.4072042	total: 2.16s	remaining: 4.85s
308:	learn: 0.4070987	total: 2.17s	remaining: 4.85s
309:	learn: 0.4069850	total: 2.18s	remaining: 4.85s
310:	learn: 0.4069314	total: 2.18s	remaining: 4.84s
311:	learn: 0.4068497	total: 2.19s	remaining: 4.83s
312:	learn: 0.4067958	total: 2.2s	remaining: 4.82s
313:	learn: 0.4067536	total: 2.2s	remaining: 4.81s
314:	learn: 0.4067133	total: 2.21s	remaining: 4.8s
315:	learn: 0.4066865	total: 2.21s	remaining: 4.79s
316:	learn: 0.4066385	total: 2.23s	remaining: 4.79s
317:	learn: 0.4065794	total: 2.23s	remaining: 4.79s
318:	learn: 0.4065044	total: 2.24s	remaining: 4.78s
319:	learn: 0.4064748	total: 2.25s	remaining: 4.77s
320:	learn: 0.4064147	total: 2.25s	remaining: 4.76s
321:	learn: 0.4062994	total: 2.26s	remaining: 4.75s
322:	learn: 0.4061969	total: 2.26s	remaining: 4.75s
323:	learn: 0.4061358	total: 2.27s	remaining: 4.74s
324:	learn: 0.4060478	total: 2.28s	remaining: 4.73s
325:	learn: 0.4060148	total: 2.29s	remaining: 4.72s
326:	learn: 0.4059479	total: 2.29s	remaining: 4.72s
327:	learn: 0.4059001	total: 2.3s	remaining: 4.71s
328:	learn: 0.4058490	total: 2.3s	remaining: 4.7s
329:	learn: 0.4057992	total: 2.31s	remaining: 4.7s
330:	learn: 0.4057147	total: 2.32s	remaining: 4.69s
331:	learn: 0.4056669	total: 2.33s	remaining: 4.68s
332:	learn: 0.4056202	total: 2.33s	remaining: 4.67s
333:	learn: 0.4055867	total: 2.34s	remaining: 4.67s
334:	learn: 0.4055295	total: 2.35s	remaining: 4.66s
335:	learn: 0.4054663	total: 2.35s	remaining: 4.65s
336:	learn: 0.4054221	total: 2.36s	remaining: 4.64s
337:	learn: 0.4053731	total: 2.37s	remaining: 4.64s
338:	learn: 0.4053346	total: 2.37s	remaining: 4.63s
339:	learn: 0.4052765	total: 2.38s	remaining: 4.62s
340:	learn: 0.4052014	total: 2.39s	remaining: 4.61s
341:	learn: 0.4051716	total: 2.39s	remaining: 4.6s
342:	learn: 0.4050251	total: 2.4s	remaining: 4.6s
343:	learn: 0.4049887	total: 2.41s	remaining: 4.59s
344:	learn: 0.4049355	total: 2.41s	remaining: 4.58s
345:	learn: 0.4048400	total: 2.42s	remaining: 4.58s
346:	learn: 0.4047795	total: 2.43s	remaining: 4.57s
347:	learn: 0.4046783	total: 2.43s	remaining: 4.56s
348:	learn: 0.4046518	total: 2.44s	remaining: 4.55s
349:	learn: 0.4046152	total: 2.45s	remaining: 4.54s
350:	learn: 0.4045283	total: 2.45s	remaining: 4.53s
351:	learn: 0.4044510	total: 2.46s	remaining: 4.53s
352:	learn: 0.4043762	total: 2.47s	remaining: 4.52s
353:	learn: 0.4043231	total: 2.47s	remaining: 4.51s
354:	learn: 0.4042147	total: 2.48s	remaining: 4.51s
355:	learn: 0.4041469	total: 2.49s	remaining: 4.5s
356:	learn: 0.4040811	total: 2.5s	remaining: 4.49s
357:	learn: 0.4040134	total: 2.5s	remaining: 4.49s
358:	learn: 0.4039581	total: 2.51s	remaining: 4.48s
359:	learn: 0.4038499	total: 2.51s	remaining: 4.47s
360:	learn: 0.4037926	total: 2.52s	remaining: 4.46s
361:	learn: 0.4037391	total: 2.53s	remaining: 4.46s
362:	learn: 0.4036359	total: 2.54s	remaining: 4.45s
363:	learn: 0.4035950	total: 2.54s	remaining: 4.45s
364:	learn: 0.4035449	total: 2.56s	remaining: 4.45s
365:	learn: 0.4034656	total: 2.57s	remaining: 4.45s
366:	learn: 0.4033914	total: 2.57s	remaining: 4.44s
367:	learn: 0.4033569	total: 2.58s	remaining: 4.43s
368:	learn: 0.4033209	total: 2.59s	remaining: 4.42s
369:	learn: 0.4032821	total: 2.59s	remaining: 4.42s
370:	learn: 0.4032514	total: 2.6s	remaining: 4.41s
371:	learn: 0.4031715	total: 2.61s	remaining: 4.4s
372:	learn: 0.4031437	total: 2.61s	remaining: 4.39s
373:	learn: 0.4030646	total: 2.62s	remaining: 4.38s
374:	learn: 0.4030244	total: 2.63s	remaining: 4.38s
375:	learn: 0.4029824	total: 2.63s	remaining: 4.37s
376:	learn: 0.4029429	total: 2.64s	remaining: 4.36s
377:	learn: 0.4028782	total: 2.65s	remaining: 4.35s
378:	learn: 0.4027823	total: 2.65s	remaining: 4.35s
379:	learn: 0.4026871	total: 2.66s	remaining: 4.34s
380:	learn: 0.4026146	total: 2.67s	remaining: 4.33s
381:	learn: 0.4025817	total: 2.67s	remaining: 4.33s
382:	learn: 0.4025417	total: 2.68s	remaining: 4.32s
383:	learn: 0.4025084	total: 2.69s	remaining: 4.31s
384:	learn: 0.4024710	total: 2.7s	remaining: 4.31s
385:	learn: 0.4024419	total: 2.7s	remaining: 4.3s
386:	learn: 0.4023730	total: 2.71s	remaining: 4.29s
387:	learn: 0.4023240	total: 2.71s	remaining: 4.28s

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num',
                                                  ColumnTransformer(transformers=[('spl',
                                                                                   SplineTransformer(degree=4,
                                                                                                     n_knots=3),
                                                                                   ['monthly_charges',
                                                                                    'total_charges']),
                                                                                  ('q',
                                                                                   QuantileTransformer(n_quantiles=100),
                                                                                   ['monthly_charges',
                                                                                    'total_charges']),
                                                                                  ('rb',
                                                                                   RobustScaler(),
                                                                                   ['monthly_charges',
                                                                                    'total_charges']),
                                                                                  ('pol',
                                                                                   Polynomial...
                                                                                   KBinsDiscretizer(encode='ordinal',
                                                                                                    strategy='uniform',
                                                                                                    subsample=None),
                                                                                   ['monthly_charges',
                                                                                    'total_charges'])]),
                                                  ['monthly_charges',
                                                   'total_charges']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 max_categories=15,
                                                                                 sparse_output=False))]),
                                                  ['type', 'payment_method',
                                                   'internet_service',
                                                   'gender'])])),
                ('model',
                 <catboost.core.CatBoostClassifier object at 0x7f82508eaa70>)])

In [33]:
prediction = pipeline.predict(X_test)

In [37]:
import yaml, joblib, json
from sklearn.model_selection import KFold, cross_validate

In [40]:
cv_strategy = KFold(n_splits=5, shuffle=True)
cv_res = cross_validate(pipeline, X_test, y_test, cv=cv_strategy, n_jobs=-1, scoring=['neg_mean_squared_log_error', 'r2'])

0:	learn: 0.6875014	total: 53ms	remaining: 52.9s
1:	learn: 0.6819499	total: 58.5ms	remaining: 29.2s
2:	learn: 0.6754661	total: 63.7ms	remaining: 21.2s
0:	learn: 0.6881158	total: 56.2ms	remaining: 56.1s
3:	learn: 0.6695242	total: 69ms	remaining: 17.2s
1:	learn: 0.6826670	total: 61.6ms	remaining: 30.7s
4:	learn: 0.6640559	total: 78.9ms	remaining: 15.7s
2:	learn: 0.6765882	total: 72.9ms	remaining: 24.2s
5:	learn: 0.6590171	total: 90.6ms	remaining: 15s
3:	learn: 0.6713817	total: 83.2ms	remaining: 20.7s
6:	learn: 0.6545178	total: 96.1ms	remaining: 13.6s
4:	learn: 0.6660787	total: 97.6ms	remaining: 19.4s
7:	learn: 0.6499590	total: 109ms	remaining: 13.5s
8:	learn: 0.6445171	total: 114ms	remaining: 12.6s
5:	learn: 0.6605997	total: 113ms	remaining: 18.7s
6:	learn: 0.6552721	total: 119ms	remaining: 16.8s
7:	learn: 0.6508821	total: 124ms	remaining: 15.4s
9:	learn: 0.6398644	total: 126ms	remaining: 12.5s
10:	learn: 0.6351415	total: 132ms	remaining: 11.8s
8:	learn: 0.6464984	total: 137ms	remaining: 15s
11:	learn: 0.6310709	total: 140ms	remaining: 11.5s
9:	learn: 0.6415503	total: 145ms	remaining: 14.4s
10:	learn: 0.6375760	total: 150ms	remaining: 13.5s
12:	learn: 0.6271481	total: 152ms	remaining: 11.5s
13:	learn: 0.6233360	total: 163ms	remaining: 11.4s
11:	learn: 0.6336853	total: 163ms	remaining: 13.4s
14:	learn: 0.6188335	total: 173ms	remaining: 11.4s
15:	learn: 0.6155703	total: 177ms	remaining: 10.9s
12:	learn: 0.6296241	total: 177ms	remaining: 13.4s
13:	learn: 0.6254909	total: 187ms	remaining: 13.2s
14:	learn: 0.6211775	total: 193ms	remaining: 12.6s
16:	learn: 0.6115926	total: 188ms	remaining: 10.9s
15:	learn: 0.6172356	total: 199ms	remaining: 12.2s
17:	learn: 0.6081087	total: 199ms	remaining: 10.9s
18:	learn: 0.6037699	total: 210ms	remaining: 10.8s
16:	learn: 0.6133950	total: 207ms	remaining: 12s
19:	learn: 0.6001390	total: 220ms	remaining: 10.8s
20:	learn: 0.5962411	total: 226ms	remaining: 10.5s
17:	learn: 0.6093605	total: 223ms	remaining: 12.2s
18:	learn: 0.6050874	total: 232ms	remaining: 12s
21:	learn: 0.5923696	total: 242ms	remaining: 10.7s
19:	learn: 0.6017877	total: 243ms	remaining: 11.9s
22:	learn: 0.5887044	total: 253ms	remaining: 10.8s
20:	learn: 0.5983493	total: 253ms	remaining: 11.8s
23:	learn: 0.5851411	total: 265ms	remaining: 10.8s
21:	learn: 0.5953827	total: 268ms	remaining: 11.9s
24:	learn: 0.5813918	total: 276ms	remaining: 10.8s
22:	learn: 0.5916791	total: 276ms	remaining: 11.7s
25:	learn: 0.5782089	total: 290ms	remaining: 10.9s
23:	learn: 0.5879531	total: 284ms	remaining: 11.6s
26:	learn: 0.5745175	total: 297ms	remaining: 10.7s
24:	learn: 0.5841335	total: 300ms	remaining: 11.7s
27:	learn: 0.5706741	total: 306ms	remaining: 10.6s
25:	learn: 0.5815107	total: 310ms	remaining: 11.6s
28:	learn: 0.5671844	total: 322ms	remaining: 10.8s
26:	learn: 0.5781009	total: 318ms	remaining: 11.5s
29:	learn: 0.5640394	total: 334ms	remaining: 10.8s
27:	learn: 0.5747050	total: 331ms	remaining: 11.5s
30:	learn: 0.5611736	total: 340ms	remaining: 10.6s
28:	learn: 0.5724613	total: 342ms	remaining: 11.5s
31:	learn: 0.5583694	total: 356ms	remaining: 10.8s
32:	learn: 0.5555116	total: 362ms	remaining: 10.6s
29:	learn: 0.5694983	total: 357ms	remaining: 11.5s
33:	learn: 0.5528136	total: 370ms	remaining: 10.5s
30:	learn: 0.5669360	total: 367ms	remaining: 11.5s
31:	learn: 0.5638855	total: 376ms	remaining: 11.4s
32:	learn: 0.5608356	total: 381ms	remaining: 11.2s
34:	learn: 0.5500920	total: 388ms	remaining: 10.7s
35:	learn: 0.5471152	total: 394ms	remaining: 10.5s
33:	learn: 0.5579047	total: 393ms	remaining: 11.2s
36:	learn: 0.5447716	total: 406ms	remaining: 10.6s
34:	learn: 0.5556193	total: 402ms	remaining: 11.1s
37:	learn: 0.5426519	total: 417ms	remaining: 10.6s
35:	learn: 0.5532289	total: 415ms	remaining: 11.1s
38:	learn: 0.5403612	total: 431ms	remaining: 10.6s
36:	learn: 0.5503210	total: 424ms	remaining: 11s
39:	learn: 0.5380948	total: 444ms	remaining: 10.7s
37:	learn: 0.5484302	total: 440ms	remaining: 11.1s
40:	learn: 0.5355614	total: 455ms	remaining: 10.6s
41:	learn: 0.5329068	total: 466ms	remaining: 10.6s
38:	learn: 0.5458007	total: 454ms	remaining: 11.2s
39:	learn: 0.5436731	total: 460ms	remaining: 11s
42:	learn: 0.5304400	total: 479ms	remaining: 10.7s
40:	learn: 0.5417543	total: 468ms	remaining: 10.9s
43:	learn: 0.5281557	total: 492ms	remaining: 10.7s
41:	learn: 0.5393559	total: 480ms	remaining: 10.9s
44:	learn: 0.5264010	total: 507ms	remaining: 10.8s
42:	learn: 0.5372172	total: 491ms	remaining: 10.9s
45:	learn: 0.5244818	total: 514ms	remaining: 10.7s
43:	learn: 0.5350941	total: 505ms	remaining: 11s
46:	learn: 0.5221162	total: 528ms	remaining: 10.7s
44:	learn: 0.5331597	total: 517ms	remaining: 11s
47:	learn: 0.5196625	total: 543ms	remaining: 10.8s
45:	learn: 0.5314295	total: 527ms	remaining: 10.9s
48:	learn: 0.5176409	total: 555ms	remaining: 10.8s
49:	learn: 0.5159240	total: 561ms	remaining: 10.7s
46:	learn: 0.5293936	total: 542ms	remaining: 11s
47:	learn: 0.5269037	total: 553ms	remaining: 11s
50:	learn: 0.5144147	total: 572ms	remaining: 10.6s
48:	learn: 0.5251394	total: 562ms	remaining: 10.9s
51:	learn: 0.5127997	total: 586ms	remaining: 10.7s
52:	learn: 0.5108170	total: 593ms	remaining: 10.6s
49:	learn: 0.5235321	total: 579ms	remaining: 11s
53:	learn: 0.5086796	total: 605ms	remaining: 10.6s
50:	learn: 0.5216517	total: 591ms	remaining: 11s
54:	learn: 0.5069512	total: 614ms	remaining: 10.6s
51:	learn: 0.5197950	total: 598ms	remaining: 10.9s
52:	learn: 0.5180767	total: 609ms	remaining: 10.9s
55:	learn: 0.5051573	total: 632ms	remaining: 10.7s
56:	learn: 0.5033665	total: 640ms	remaining: 10.6s
53:	learn: 0.5161733	total: 625ms	remaining: 10.9s
57:	learn: 0.5021843	total: 652ms	remaining: 10.6s
54:	learn: 0.5147326	total: 638ms	remaining: 11s
58:	learn: 0.5008180	total: 664ms	remaining: 10.6s
55:	learn: 0.5129329	total: 653ms	remaining: 11s
59:	learn: 0.4988660	total: 678ms	remaining: 10.6s
56:	learn: 0.5115623	total: 664ms	remaining: 11s
57:	learn: 0.5101438	total: 670ms	remaining: 10.9s
60:	learn: 0.4971065	total: 694ms	remaining: 10.7s
61:	learn: 0.4952803	total: 700ms	remaining: 10.6s
58:	learn: 0.5087400	total: 686ms	remaining: 10.9s
59:	learn: 0.5067846	total: 692ms	remaining: 10.8s
62:	learn: 0.4935382	total: 712ms	remaining: 10.6s
60:	learn: 0.5051648	total: 702ms	remaining: 10.8s
63:	learn: 0.4922257	total: 730ms	remaining: 10.7s
64:	learn: 0.4906911	total: 736ms	remaining: 10.6s
61:	learn: 0.5035395	total: 715ms	remaining: 10.8s
62:	learn: 0.5019564	total: 721ms	remaining: 10.7s
65:	learn: 0.4894945	total: 743ms	remaining: 10.5s
66:	learn: 0.4877507	total: 751ms	remaining: 10.5s
63:	learn: 0.5006331	total: 734ms	remaining: 10.7s
67:	learn: 0.4861974	total: 756ms	remaining: 10.4s
68:	learn: 0.4847933	total: 765ms	remaining: 10.3s
69:	learn: 0.4835680	total: 771ms	remaining: 10.2s
70:	learn: 0.4823292	total: 777ms	remaining: 10.2s
64:	learn: 0.4995854	total: 757ms	remaining: 10.9s
71:	learn: 0.4809149	total: 786ms	remaining: 10.1s
72:	learn: 0.4796811	total: 792ms	remaining: 10.1s
65:	learn: 0.4982431	total: 774ms	remaining: 10.9s
73:	learn: 0.4784995	total: 801ms	remaining: 10s
66:	learn: 0.4969397	total: 783ms	remaining: 10.9s
74:	learn: 0.4772451	total: 814ms	remaining: 10s
67:	learn: 0.4959978	total: 796ms	remaining: 10.9s
75:	learn: 0.4761525	total: 824ms	remaining: 10s
68:	learn: 0.4950052	total: 807ms	remaining: 10.9s
76:	learn: 0.4750744	total: 838ms	remaining: 10s
69:	learn: 0.4936855	total: 818ms	remaining: 10.9s
77:	learn: 0.4741972	total: 851ms	remaining: 10.1s
70:	learn: 0.4925328	total: 832ms	remaining: 10.9s
78:	learn: 0.4731269	total: 864ms	remaining: 10.1s
71:	learn: 0.4914239	total: 844ms	remaining: 10.9s
79:	learn: 0.4718407	total: 874ms	remaining: 10.1s
72:	learn: 0.4904353	total: 856ms	remaining: 10.9s
80:	learn: 0.4709842	total: 887ms	remaining: 10.1s
73:	learn: 0.4892260	total: 872ms	remaining: 10.9s
81:	learn: 0.4699574	total: 898ms	remaining: 10.1s
74:	learn: 0.4882589	total: 884ms	remaining: 10.9s
82:	learn: 0.4685720	total: 911ms	remaining: 10.1s
83:	learn: 0.4676359	total: 922ms	remaining: 10.1s
75:	learn: 0.4869803	total: 900ms	remaining: 10.9s
84:	learn: 0.4666440	total: 937ms	remaining: 10.1s
76:	learn: 0.4855309	total: 912ms	remaining: 10.9s
85:	learn: 0.4657338	total: 949ms	remaining: 10.1s
77:	learn: 0.4844889	total: 926ms	remaining: 10.9s
86:	learn: 0.4647240	total: 960ms	remaining: 10.1s
78:	learn: 0.4833665	total: 939ms	remaining: 10.9s
87:	learn: 0.4640922	total: 975ms	remaining: 10.1s
79:	learn: 0.4825063	total: 952ms	remaining: 10.9s
88:	learn: 0.4633262	total: 988ms	remaining: 10.1s
80:	learn: 0.4813819	total: 965ms	remaining: 11s
89:	learn: 0.4626775	total: 1s	remaining: 10.1s
81:	learn: 0.4804117	total: 979ms	remaining: 11s
90:	learn: 0.4618348	total: 1.01s	remaining: 10.1s
82:	learn: 0.4794073	total: 992ms	remaining: 11s
91:	learn: 0.4609847	total: 1.02s	remaining: 10.1s
92:	learn: 0.4602405	total: 1.04s	remaining: 10.1s
83:	learn: 0.4785524	total: 1.01s	remaining: 11s
93:	learn: 0.4594242	total: 1.05s	remaining: 10.1s
84:	learn: 0.4774324	total: 1.02s	remaining: 11s
94:	learn: 0.4586723	total: 1.06s	remaining: 10.1s
85:	learn: 0.4763784	total: 1.04s	remaining: 11s
95:	learn: 0.4580492	total: 1.07s	remaining: 10.1s
86:	learn: 0.4755306	total: 1.05s	remaining: 11s
96:	learn: 0.4574059	total: 1.08s	remaining: 10.1s
97:	learn: 0.4566574	total: 1.1s	remaining: 10.1s
87:	learn: 0.4747041	total: 1.06s	remaining: 11s
98:	learn: 0.4558610	total: 1.11s	remaining: 10.1s
88:	learn: 0.4737973	total: 1.07s	remaining: 11s
99:	learn: 0.4549919	total: 1.12s	remaining: 10.1s
89:	learn: 0.4730210	total: 1.08s	remaining: 11s
100:	learn: 0.4543423	total: 1.13s	remaining: 10.1s
90:	learn: 0.4722673	total: 1.1s	remaining: 11s
101:	learn: 0.4535992	total: 1.14s	remaining: 10s
91:	learn: 0.4715144	total: 1.11s	remaining: 11s
102:	learn: 0.4528712	total: 1.15s	remaining: 10s
92:	learn: 0.4707885	total: 1.12s	remaining: 10.9s
103:	learn: 0.4522418	total: 1.16s	remaining: 10s
93:	learn: 0.4699242	total: 1.13s	remaining: 10.9s
104:	learn: 0.4513613	total: 1.18s	remaining: 10s
105:	learn: 0.4505580	total: 1.19s	remaining: 10s
94:	learn: 0.4690026	total: 1.15s	remaining: 10.9s
106:	learn: 0.4499147	total: 1.2s	remaining: 10s
95:	learn: 0.4683096	total: 1.16s	remaining: 10.9s
107:	learn: 0.4490585	total: 1.21s	remaining: 10s
96:	learn: 0.4677007	total: 1.18s	remaining: 10.9s
108:	learn: 0.4482669	total: 1.22s	remaining: 10s
97:	learn: 0.4669578	total: 1.19s	remaining: 10.9s
109:	learn: 0.4475145	total: 1.23s	remaining: 9.99s
98:	learn: 0.4659757	total: 1.2s	remaining: 10.9s
110:	learn: 0.4468362	total: 1.25s	remaining: 9.98s
111:	learn: 0.4459329	total: 1.26s	remaining: 9.98s
99:	learn: 0.4651117	total: 1.22s	remaining: 11s
112:	learn: 0.4453921	total: 1.27s	remaining: 9.97s
100:	learn: 0.4644338	total: 1.23s	remaining: 11s
113:	learn: 0.4446259	total: 1.28s	remaining: 9.95s
101:	learn: 0.4635610	total: 1.24s	remaining: 10.9s
114:	learn: 0.4440449	total: 1.29s	remaining: 9.94s
102:	learn: 0.4629538	total: 1.25s	remaining: 10.9s
115:	learn: 0.4435732	total: 1.31s	remaining: 9.96s
116:	learn: 0.4432245	total: 1.31s	remaining: 9.93s
103:	learn: 0.4623930	total: 1.27s	remaining: 11s
117:	learn: 0.4426103	total: 1.33s	remaining: 9.94s
104:	learn: 0.4617025	total: 1.28s	remaining: 10.9s
118:	learn: 0.4420554	total: 1.34s	remaining: 9.94s
105:	learn: 0.4611110	total: 1.3s	remaining: 10.9s
119:	learn: 0.4412873	total: 1.35s	remaining: 9.92s
106:	learn: 0.4603681	total: 1.31s	remaining: 10.9s
120:	learn: 0.4407460	total: 1.36s	remaining: 9.9s
107:	learn: 0.4598084	total: 1.32s	remaining: 10.9s
121:	learn: 0.4402158	total: 1.37s	remaining: 9.89s
122:	learn: 0.4394674	total: 1.38s	remaining: 9.87s
108:	learn: 0.4590347	total: 1.34s	remaining: 10.9s
123:	learn: 0.4391175	total: 1.4s	remaining: 9.87s
109:	learn: 0.4580923	total: 1.35s	remaining: 10.9s
124:	learn: 0.4383627	total: 1.41s	remaining: 9.9s
110:	learn: 0.4575737	total: 1.37s	remaining: 10.9s
125:	learn: 0.4378351	total: 1.43s	remaining: 9.9s
111:	learn: 0.4571222	total: 1.38s	remaining: 11s
126:	learn: 0.4370888	total: 1.44s	remaining: 9.89s
112:	learn: 0.4565985	total: 1.39s	remaining: 10.9s
127:	learn: 0.4367052	total: 1.45s	remaining: 9.87s
113:	learn: 0.4560396	total: 1.41s	remaining: 10.9s
128:	learn: 0.4362678	total: 1.46s	remaining: 9.87s
114:	learn: 0.4556093	total: 1.42s	remaining: 10.9s
129:	learn: 0.4357728	total: 1.47s	remaining: 9.86s
130:	learn: 0.4352831	total: 1.49s	remaining: 9.87s
115:	learn: 0.4550966	total: 1.43s	remaining: 10.9s
131:	learn: 0.4346887	total: 1.5s	remaining: 9.87s
116:	learn: 0.4542955	total: 1.45s	remaining: 10.9s
132:	learn: 0.4338673	total: 1.51s	remaining: 9.86s
117:	learn: 0.4537325	total: 1.46s	remaining: 10.9s
133:	learn: 0.4333226	total: 1.52s	remaining: 9.86s
118:	learn: 0.4529553	total: 1.48s	remaining: 10.9s
134:	learn: 0.4328581	total: 1.54s	remaining: 9.84s
119:	learn: 0.4523831	total: 1.49s	remaining: 10.9s
135:	learn: 0.4323415	total: 1.55s	remaining: 9.86s
120:	learn: 0.4518095	total: 1.5s	remaining: 10.9s
136:	learn: 0.4319183	total: 1.56s	remaining: 9.86s
121:	learn: 0.4514762	total: 1.51s	remaining: 10.9s
137:	learn: 0.4313047	total: 1.58s	remaining: 9.86s
122:	learn: 0.4509010	total: 1.53s	remaining: 10.9s
138:	learn: 0.4308317	total: 1.59s	remaining: 9.86s
139:	learn: 0.4305417	total: 1.6s	remaining: 9.84s
123:	learn: 0.4501856	total: 1.54s	remaining: 10.9s
140:	learn: 0.4300482	total: 1.61s	remaining: 9.83s
124:	learn: 0.4498153	total: 1.56s	remaining: 10.9s
141:	learn: 0.4297922	total: 1.63s	remaining: 9.82s
125:	learn: 0.4493990	total: 1.57s	remaining: 10.9s
142:	learn: 0.4291735	total: 1.64s	remaining: 9.83s
126:	learn: 0.4488764	total: 1.58s	remaining: 10.9s
143:	learn: 0.4287089	total: 1.65s	remaining: 9.82s
127:	learn: 0.4483442	total: 1.59s	remaining: 10.9s
144:	learn: 0.4283866	total: 1.66s	remaining: 9.81s
128:	learn: 0.4477796	total: 1.61s	remaining: 10.9s
145:	learn: 0.4281494	total: 1.67s	remaining: 9.79s
146:	learn: 0.4277917	total: 1.68s	remaining: 9.77s
129:	learn: 0.4473072	total: 1.62s	remaining: 10.9s
147:	learn: 0.4274891	total: 1.7s	remaining: 9.77s
130:	learn: 0.4469767	total: 1.64s	remaining: 10.9s
148:	learn: 0.4268348	total: 1.71s	remaining: 9.77s
131:	learn: 0.4465283	total: 1.65s	remaining: 10.8s
149:	learn: 0.4263272	total: 1.72s	remaining: 9.76s
132:	learn: 0.4462132	total: 1.66s	remaining: 10.8s
150:	learn: 0.4260189	total: 1.74s	remaining: 9.76s
133:	learn: 0.4457262	total: 1.67s	remaining: 10.8s
151:	learn: 0.4256239	total: 1.75s	remaining: 9.76s
134:	learn: 0.4453434	total: 1.69s	remaining: 10.8s
152:	learn: 0.4250893	total: 1.76s	remaining: 9.76s
135:	learn: 0.4446541	total: 1.7s	remaining: 10.8s
153:	learn: 0.4247788	total: 1.77s	remaining: 9.74s
136:	learn: 0.4442563	total: 1.71s	remaining: 10.8s
154:	learn: 0.4244814	total: 1.78s	remaining: 9.72s
137:	learn: 0.4439028	total: 1.72s	remaining: 10.7s
155:	learn: 0.4241247	total: 1.79s	remaining: 9.7s
156:	learn: 0.4236671	total: 1.8s	remaining: 9.68s
138:	learn: 0.4432736	total: 1.74s	remaining: 10.8s
157:	learn: 0.4232753	total: 1.81s	remaining: 9.67s
139:	learn: 0.4427229	total: 1.75s	remaining: 10.8s
158:	learn: 0.4227335	total: 1.83s	remaining: 9.67s
140:	learn: 0.4424162	total: 1.77s	remaining: 10.8s
159:	learn: 0.4222833	total: 1.84s	remaining: 9.67s
160:	learn: 0.4219252	total: 1.85s	remaining: 9.65s
141:	learn: 0.4420797	total: 1.78s	remaining: 10.8s
161:	learn: 0.4214517	total: 1.86s	remaining: 9.63s
142:	learn: 0.4413876	total: 1.79s	remaining: 10.8s
162:	learn: 0.4211462	total: 1.87s	remaining: 9.62s
163:	learn: 0.4205742	total: 1.88s	remaining: 9.6s
143:	learn: 0.4409874	total: 1.81s	remaining: 10.8s
164:	learn: 0.4202357	total: 1.9s	remaining: 9.59s
144:	learn: 0.4404890	total: 1.82s	remaining: 10.8s
165:	learn: 0.4199979	total: 1.91s	remaining: 9.58s
145:	learn: 0.4398575	total: 1.83s	remaining: 10.7s
166:	learn: 0.4198123	total: 1.92s	remaining: 9.57s
167:	learn: 0.4195249	total: 1.93s	remaining: 9.57s
146:	learn: 0.4395473	total: 1.86s	remaining: 10.8s
147:	learn: 0.4390963	total: 1.87s	remaining: 10.7s
168:	learn: 0.4191415	total: 1.95s	remaining: 9.57s
169:	learn: 0.4188953	total: 1.96s	remaining: 9.55s
148:	learn: 0.4384944	total: 1.88s	remaining: 10.7s
170:	learn: 0.4184148	total: 1.97s	remaining: 9.55s
149:	learn: 0.4380301	total: 1.89s	remaining: 10.7s
171:	learn: 0.4181126	total: 1.98s	remaining: 9.54s
150:	learn: 0.4377868	total: 1.91s	remaining: 10.7s
172:	learn: 0.4178697	total: 1.99s	remaining: 9.53s
151:	learn: 0.4375182	total: 1.92s	remaining: 10.7s
173:	learn: 0.4175710	total: 2.01s	remaining: 9.52s
152:	learn: 0.4372162	total: 1.93s	remaining: 10.7s
174:	learn: 0.4173247	total: 2.02s	remaining: 9.53s
153:	learn: 0.4367228	total: 1.94s	remaining: 10.7s
175:	learn: 0.4171446	total: 2.04s	remaining: 9.53s
154:	learn: 0.4363975	total: 1.96s	remaining: 10.7s
176:	learn: 0.4167948	total: 2.05s	remaining: 9.53s
155:	learn: 0.4360791	total: 1.97s	remaining: 10.7s
177:	learn: 0.4166159	total: 2.06s	remaining: 9.52s
156:	learn: 0.4355320	total: 1.99s	remaining: 10.7s
178:	learn: 0.4162479	total: 2.07s	remaining: 9.52s
157:	learn: 0.4352331	total: 2s	remaining: 10.6s
179:	learn: 0.4160691	total: 2.09s	remaining: 9.51s
158:	learn: 0.4349673	total: 2.01s	remaining: 10.6s
180:	learn: 0.4159422	total: 2.1s	remaining: 9.5s
159:	learn: 0.4346419	total: 2.02s	remaining: 10.6s
181:	learn: 0.4156668	total: 2.11s	remaining: 9.48s
160:	learn: 0.4341932	total: 2.04s	remaining: 10.6s
182:	learn: 0.4155128	total: 2.12s	remaining: 9.47s
161:	learn: 0.4338931	total: 2.05s	remaining: 10.6s
183:	learn: 0.4150593	total: 2.14s	remaining: 9.47s
162:	learn: 0.4334309	total: 2.06s	remaining: 10.6s
184:	learn: 0.4147814	total: 2.15s	remaining: 9.47s
163:	learn: 0.4332247	total: 2.07s	remaining: 10.6s
185:	learn: 0.4144642	total: 2.16s	remaining: 9.45s
164:	learn: 0.4329758	total: 2.08s	remaining: 10.5s
186:	learn: 0.4139448	total: 2.17s	remaining: 9.45s
165:	learn: 0.4326991	total: 2.09s	remaining: 10.5s
166:	learn: 0.4324192	total: 2.1s	remaining: 10.5s
187:	learn: 0.4136149	total: 2.19s	remaining: 9.45s
188:	learn: 0.4134354	total: 2.2s	remaining: 9.43s
167:	learn: 0.4319708	total: 2.12s	remaining: 10.5s
189:	learn: 0.4132816	total: 2.21s	remaining: 9.43s
168:	learn: 0.4316445	total: 2.13s	remaining: 10.5s
190:	learn: 0.4131434	total: 2.22s	remaining: 9.42s
169:	learn: 0.4314391	total: 2.14s	remaining: 10.5s
191:	learn: 0.4127864	total: 2.23s	remaining: 9.41s
170:	learn: 0.4310429	total: 2.15s	remaining: 10.4s
192:	learn: 0.4126096	total: 2.25s	remaining: 9.39s
171:	learn: 0.4307159	total: 2.17s	remaining: 10.4s
193:	learn: 0.4122716	total: 2.26s	remaining: 9.38s
172:	learn: 0.4301163	total: 2.18s	remaining: 10.4s
194:	learn: 0.4119454	total: 2.27s	remaining: 9.38s
173:	learn: 0.4297178	total: 2.19s	remaining: 10.4s
195:	learn: 0.4115344	total: 2.29s	remaining: 9.37s
174:	learn: 0.4293931	total: 2.21s	remaining: 10.4s
196:	learn: 0.4113040	total: 2.29s	remaining: 9.35s
175:	learn: 0.4292083	total: 2.22s	remaining: 10.4s
197:	learn: 0.4110036	total: 2.31s	remaining: 9.35s
176:	learn: 0.4287271	total: 2.23s	remaining: 10.4s
198:	learn: 0.4108132	total: 2.32s	remaining: 9.34s
177:	learn: 0.4282186	total: 2.24s	remaining: 10.4s
199:	learn: 0.4106163	total: 2.33s	remaining: 9.33s
178:	learn: 0.4279029	total: 2.25s	remaining: 10.3s
200:	learn: 0.4104252	total: 2.35s	remaining: 9.32s
179:	learn: 0.4276143	total: 2.27s	remaining: 10.3s
201:	learn: 0.4102915	total: 2.36s	remaining: 9.31s
202:	learn: 0.4101387	total: 2.37s	remaining: 9.29s
180:	learn: 0.4271339	total: 2.28s	remaining: 10.3s
203:	learn: 0.4099054	total: 2.38s	remaining: 9.28s
181:	learn: 0.4268621	total: 2.29s	remaining: 10.3s
182:	learn: 0.4267146	total: 2.31s	remaining: 10.3s
204:	learn: 0.4095970	total: 2.39s	remaining: 9.28s
183:	learn: 0.4263456	total: 2.32s	remaining: 10.3s
205:	learn: 0.4093626	total: 2.4s	remaining: 9.27s

In [42]:
with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    model_info = mlflow.sklearn.log_model(sk_model=pipeline,
                            artifact_path="models",
                            registered_model_name=REGISTRY_MODEL_NAME,
                            )

Registered model 'PREPROCESSED_MODEL' already exists. Creating a new version of this model...
2026/01/14 09:41:12 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: PREPROCESSED_MODEL, version 2
Created version '2' of model 'PREPROCESSED_MODEL'.

In [45]:
from mlflow import MlflowClient

In [46]:
client = MlflowClient()

In [49]:
EXP = client.get_experiment_by_name(EXPERIMENT_NAME)

In [54]:
versions = client.search_model_versions(f"name='{REGISTRY_MODEL_NAME}'")

In [58]:
run_id

'2b32f528461c4516854050eb4fabfd7b'